/**
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 1,2,3,5,8,13,21,34,55,89,...
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

public class ProblemTwo {
    static void run() {
        int sumOfEvens = 2
        int firstNum = 1
        int secondNum = 2
        int tempNum = 0

        while ((firstNum + secondNum) <= 4000000) {
            tempNum = firstNum + secondNum
            if (isEven(tempNum)) {
                sumOfEvens += tempNum
            }
            if (firstNum > secondNum) {
                secondNum = tempNum
            } else {
                firstNum = tempNum
            }
        }
        println "sumOfEvens is: " + sumOfEvens
    }

    static boolean isEven (int num) {
        return (num.mod(2) == 0)
    }
}